"use client";
import "./globals.css";
import Navbar from "../components/navbar";
import Footer from "../components/Footer";
import { Poppins } from "next/font/google";
import localFont from "@next/font/local";
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
} from "@web3modal/ethereum";
import { Web3Modal } from "@web3modal/react";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { arbitrum, mainnet, polygon } from "viem/chains";
import { ScrollProvider } from "@/context/ScrollContext";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

const monument = localFont({
  src: "../../public/fonts/MonumentExtended-Ultrabold.otf",
  variable: "--font-monument",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const metadata = {
  name: "Web3Modal",
  description: "Web3Modal Example",
  url: "https://web3modal.com",
  icons: ["https://avatars.githubusercontent.com/u/37784886"],
};

const projectId = "502577a6cea277332cb444a0a9306cf4";
const chains = [arbitrum, mainnet, polygon];

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })]);
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, chains }),
  publicClient,
});
const ethereumClient = new EthereumClient(wagmiConfig, chains);

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" className="light">
        <body
          className={`${poppins.className} ${monument.variable} scrollbar-thin scrollbar-thumb-[#BC96E6] scrollbar-track-[#242F40] scrollbar-rounded`}
        >
          <WagmiConfig config={wagmiConfig}>
            <ScrollProvider>
              <Navbar />
              {children}
              <Footer />
            </ScrollProvider>
          </WagmiConfig>
          <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
        </body>
      </html>
    </>
  );
}
